version: '3.8'

services:
  app:
    build: .
    env_file: ./.env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped

  db:
    image: postgres:15
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
